### ISSUE TITLE
MysteryBox (mysql)

### ISSUE THREAD

**Issue by xDamijan** [OnlyNoobDied/GadgetsMenu#128]
Hi so i can't make cross server Mysterybox and Mysterydust... but funny is that other plugins working great (pex, nametag..)

**Comment by OnlyNoobDied** [comment]
by changing this in your config to link mystery dust to mysql.
```
Purchase System:
  # What storage you want to save Mystery Dust, or link it to other plugin.
  # Available Storages:  file, mysql, vault, playerpoints
  Storage: mysql
```

**Comment by xDamijan** [comment]
Doesnt work at all..

**Comment by OnlyNoobDied** [comment]
if you want to use mysql to save data. You need to setup this
```
# Set your settings for player-data storage.
Player-Data:
  
  # Set to true to enable MySQL database.
  Database: true
  MySQL:
    hostname: localhost
    username: root
    database: minecraft
    port: '3306'
    password: password
```
