### ISSUE TITLE
[Suggestion] The mobgun gadget. Add option to translate mobs names

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#189]
Hi,

Is it possible for you to add a launguage API or an option to allow me to translate mobs names?
So I can use my main server language instead of english names ;)

Thank you so much.

**Comment by OnlyNoobDied** [comment]
You are able to edit mob name in the next updates.
```
      MobGun:
        Name: '&9MobGun Gadget'
        Cooldown: 30
        Mystery Dust: 28
        Rarity: Rare
        Enabled: true
        CanBeFound: true
        Purchasable: true
        Lore:
        - '&7Launch exploding'
        - '&7projectiles using 18'
        - '&7different types of mobs.'
        Actionbar-Message: '{GADGET} &r- &6{MOB}'
        Mob-Name:
          Pig: Pig
          Villager: Villager
          Ocelot: Ocelot
          Cow: Cow
          Creeper: Creeper
          Spider: Spider
          Squid: Squid
          Chicken: Chicken
          Sheep: Sheep
          Wolf: Wolf
          Witch: Witch
          Blaze: Blaze
          Horse: Horse
          Zombie: Zombie
          Skeleton: Skeleton
          MushroomCow: MushroomCow
          CaveSpider: CaveSpider
          PigZombie: PigZombie
```
