### ISSUE TITLE
Mystery Vault file reset on server start

### ISSUE THREAD

**Issue by PikachuEXE** [OnlyNoobDied/GadgetsMenu#219]
### Env
- Spigot 1.11.2
- GadgetsMenu-3.7.8

### Config
Vault file:
```yaml
Mystery Vault:
  '1':
    Location:
      world: galaxy__survival_main
      x: -238.0
      y: 63.0
      z: -64.0
    BlockFace: SOUTH
```
Config: 
[config.yml.txt](https://github.com/OnlyNoobDied/GadgetsMenu/files/1099262/config.yml.txt)

### Log
Log file on startup: 
[latest.zip](https://github.com/OnlyNoobDied/GadgetsMenu/files/1099274/latest.zip)

No error from the plugin
