### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#271]
When there is a category that has a sub-category it shows  like this:

---------------------
Status: UNLOCKED
Unlocked: 4/4
---------------------

What if... there are 2/4 unlocked? will it show as LOCKED or UNLOCKED?
when there is a sub-category it should be like this:

---------------------
Unlocked: 4/4
---------------------

**Comment by OnlyNoobDied** [comment]
modify these option in your config file
```
Permission:
  No-Permission:
    Show-In-Lore: false <-- set to false
  Has-Permission:
    Show-In-Lore: false <-- set to false
```
