### ISSUE TITLE
Mysterybox message doesn't show for non op players

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#329]
The message that is supposed to be sent to the players of what items they got doesn't show. It shows for me when I am oped but not for them

**Comment by maxlehot1234** [comment]
It works great for me, but I disable everything EXCEPT for the biggest crate to prevent chat spamming.

On 4.0.0, the dev add something in mystery boxes.yml something for EACH box.

**Comment by HellaMixel** [comment]
They are all enabeled

**Comment by HellaMixel** [comment]
I have them all enabeled just because MysteryBoxes won't be that easy for optain on my server

**Comment by OnlyNoobDied** [comment]
is this the message you talk about?
```
    Found-Loot:
      Common:
        Enabled: true
        Message: '&b[Mystery Box] {PLAYER} &bfound a &aCommon {LOOT}&b!'
      Rare:
        Enabled: true
        Message: '&b[Mystery Box] {PLAYER} &bfound a &9Rare {LOOT}&b!'
      Epic:
        Enabled: true
        Message: '&b[Mystery Box] {PLAYER} &bfound a &5Epic {LOOT}&b!'
      Legendary:
        Enabled: true
        Message: '&b[Mystery Box] {PLAYER} &bfound a &6Legendary {LOOT}&b!'
```
