### ISSUE TITLE
[FEATURE] Discount permission to buy cosmetics

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#374]
Hi, are you able to add a discounts.yml?

In this file, we can have something like this:
https://pastebin.com/pwTrk6wN

So whit this, I can give player a cosmetics cost discount for events, donators, etc.

Thank you so much if you can ;)

**Comment by OnlyNoobDied** [comment]
May i ask which section do you want to add?
Craft Mystery Boxes or Cosmetic items

**Comment by maxlehot1234** [comment]
Cosmetics items.

So if a player have: cosmetics.discount.10 every cosmetics will cost 10% less ;)

It could be nice for donators or really useful for server events ;)

**Comment by TheIntelloBox** [comment]
Could you add it please ? :)

**Comment by Matocolotoe** [comment]
Yeah it would be a very nice feature.

**Comment by TheIntelloBox** [comment]
I agree with you ! :D

**Comment by OnlyNoobDied** [comment]
This feature requested almost 1 year and now this feature will be added in the next update.

**Comment by TheIntelloBox** [comment]
Oh my god fantastic ! :D

**Comment by OnlyNoobDied** [comment]
```
Item-Cost-Discount:
  Enabled: true
  Discount:
    Cosmetic-Item: true
    Crafting-Mystery-Box: true
  Discount-Rates:
    # The name of the discount group.
    # Use for placeholder.
    # Syntax: {<name>_MYSTERY_DUST}
    # Get the cost of that discount rate.
    VIP:
      # Higher numbers override.
      Priority: 1
      # Permission to
      Permission: gadgetsmenu.discount.VIP
      # Discount rates.
      Rate: 20
      Lore:
        Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - '&aVIP&7: &a{VIP_MYSTERY_DUST} &7Mystery Dust (&a20% &7OFF!) &e\u25C0'
        - '&cMVP: {MVP_MYSTERY_DUST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &a{VIP_MYSTERY_DUST} &7Mystery Dust'
        - '&eClick to craft!'
        Not-Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - "&aVIP&7: &a{VIP_MYSTERY_DUST} &7Mystery Dust (&a20% &7OFF!) &e\u25C0"
        - '&cMVP: {MVP_MYSTERY_DUST} Mystery Dust (40% OFF!)'
        - ''
        - '&7Your Cost: &c{VIP_MYSTERY_DUST} &7Mystery Dust'
        - '&cYou need &b{SURPLUS_MYSTERY_DUST} &cmore mystery dust!'
    MVP:
      Priority: 2
      Permission: gadgetsmenu.discount.MVP
      Rate: 40
      Lore:
        Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - '&8&mVIP: {MVP_MYSTERY_DUST} Mystery Dust (20% OFF!) '
        - '&bMVP&7: &a{MVP_MYSTERY_DUST} &7Mystery Dust (&a40% &7OFF!) &e\u25C0'
        - ''
        - '&7Your Cost: &a{MVP_MYSTERY_DUST} &7Mystery Dust'
        - '&eClick to craft!'
        Not-Enough-Mystery-Dust:
        - ''
        - '&8&mRegular: {MYSTERY_DUST} Mystery Dust!'
        - '&8&mVIP: {VIP_MYSTERY_DUST} Mystery Dust (20% OFF!) '
        - "&bMVP&7: &a{MVP_MYSTERY_DUST} &7Mystery Dust (&a40% &7OFF!) &e\u25C0"
        - ''
        - '&7Your Cost: &a{MVP_MYSTERY_DUST} &7Mystery Dust'
        - '&cYou need &b{SURPLUS_MYSTERY_DUST} &cmore mystery dust!'
```
Any problem/ideas about this?
