### ISSUE TITLE
Mystery Box

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#421]
Can you add to mystery box config something like this:

equip-loot: true/false

when you open mystery box and found something it automatic equip your cosmetics.

For example I found Trampoline in Mystery Box and this automatic execute /gmenu eguip gadget trampoline.

Please, add this in next update, thanks.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
```
Settings:
  # Auto equip cosmetic after player purchase.
  Auto-Equip-After-Purchase: true
  # Auto equip cosmetic when player found loot from mystery box.
  Auto-Equip-On-Loot-Found: true
```
