### ISSUE TITLE
Players are auto-equip

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#470]
Hi, i disabled the auto-equip function and negate the permissions, but it continue to work for players :(

**Comment by OnlyNoobDied** [comment]
If player have these permissions, it will still auto equip the cosmetic.

```
gadgetsmenu.autoequip.*:
 - gadgetsmenu.autoequip.purchase
 - gadgetsmenu.autoequip.foundloot
```

**Comment by maxlehot1234** [comment]
I negate the permission so they are not supposed to have auto equip 

jeudi 4 janvier 2018 06:08 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
Just notice this setting.
```
Settings:
  Auto-Equip-After-Purchase: true
  # Auto equip cosmetic when player found loot from mystery box.
  Auto-Equip-On-Loot-Found: true
```
Set to false to disable auto-equip.
