### ISSUE TITLE
Idea for custom hats

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#588]
Hello, can you add way to create custom hats using id? Bed on player's head looks very cool.

```
Custom-Hats:
  bed:
    Name: '&cRed Bed'
    Mystery Dust: 2
    Rarity: Legendary
    Id: 355
    Data: 14
    Enabled: true
    CanBeFound: true
    Purchasable: true
```
