### ISSUE TITLE
Change Menu-Item lore=reset config

### ISSUE THREAD

**Issue by GuerreroCraft61** [OnlyNoobDied/GadgetsMenu#594]
```
Menu-Item:
  Name: '&aGadgetsMenu'
  Material: '399:0'
   Slot: 0-8
  Slot: 4
  Give-On-Join: true
  Able-To-Move: false
  Lore:
  - '&7Polvo misterioso: &b{MYSTERY_DUST}'
  - '&7MysteryBox: &b{MYSTERY_BOXES}'
  - ''
  - '&7Disfruta de divertidas funciones cosmeticas!'
  - '&7se añadiran mas cosas con el tiempo'
  - '&7Consulta nuestro discord para actualizaciones'
  - '&7Gracias por apoyar a nuestro servidor.'
```
I translate it and it reset my config
