### ISSUE TITLE
Mystery Dust not using Database

### ISSUE THREAD

**Issue by felix425** [OnlyNoobDied/GadgetsMenu#631]
Hey,
I'm using the mysql mode and i have the problem that the plugin still uses the user data files to store mystery dust and ignores the Database only for this value.

**Comment by OnlyNoobDied** [comment]
```
Cosmetic-Item-Purchase:
  # Set to true allows player to purchase cosmetic items.
  Enabled: true
  # Set the storage where do you want to save mystery dust.
  # Available storages: 'file', 'mysql', 'coins-jasperjh', 'coinsapi', 'playerpoints', 'vault'.
  Mystery-Dust-Storage: file
```
Set the mystery dust storage to `mysql`
