### ISSUE TITLE
Head texture not working for option "Show-Custom-Item"

### ISSUE THREAD

**Issue by Endothelium** [OnlyNoobDied/GadgetsMenu#661]
I want to  set the show-custom-item of No-Permission category as custom player head.

```
  No-Permission:
    Show-Custom-Item:
      Enabled: true
      Material: 'head:638c53e66f28cf2c7fb1523c9e5de1ae0cf4d7a1faf553e752494a8d6d2e32'
```
But it only show  Steve Head.

It's not a problem with the texture, because if i use the same texture string in custom_hats.yml, it does work.

 - Server Version: 1.13.2
 - GadgetsMenu Version:  4.3.6

![image](https://user-images.githubusercontent.com/11161697/53695103-b36bb280-3db7-11e9-96ec-70d55e96ad07.png)

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.

**Comment by Endothelium** [comment]
Hello,

The new update fix it for the Show-Custom-Item options in config.yml,

but not for mystery box craft menu. for example

```
  Mystery-Box-Crafting-Menu:
    GUI-Name: "&9✦ &dCoffre Style &7&l- &9Craft ✦"
    Items:
      1-Star:
        Name: '&9✦ &dCoffre Style &7&l- &9Commun ✦'
        Material: 'head:78f88b161763f62e4c51f5eb1d38faf3b82c48a839ac3171229557ade427434'
        Price: 3
        Lore:
        - ''
        - '&7Qualité: &e✰&7✰✰✰✰'
        - ''
        - '&7Contient de nombreux Styles &apeu rares.'
        - ''
        - '&7Il peut néanmoins contenir des Styles'
        - '&7&aplus rares &7et même &6Légendaires!'
```

And the Textures: <url> syntax doesnt work neither
