### ISSUE TITLE
Disable the load line

### ISSUE THREAD

**Issue by ItsBrendy** [OnlyNoobDied/GadgetsMenu#725]
Make it possible to disable the load line that is appearing after use of a cosmetic

**Comment by OnlyNoobDied** [comment]
You can bypass cooldown timer in settings using command or click the item in main menu.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Commands#gmenu-settings-setting-value


If you want to disable the cooldown timer, you can do that in `messages.yml`
```
Cooldown-In-Action-Bar:
  Enabled: true
  Cooldown-Block:
    Remain: '&c|'
    Retain: '&a|'
    Amount-Of-Blocks: 100
  Cooldown-Message: '{NAME} &f{COOLDOWN_BLOCK} &f{TIME_LEFT}s'
```
