### ISSUE TITLE
Playerpoints purchase method

### ISSUE THREAD

**Issue by VTSTG233** [OnlyNoobDied/GadgetsMenu#796]
Gadgetsmenu / categories / props
For example:
Mystery Dust: 15
Rarity: Common
Enabled: true
CanBeFound: true
Purchasable: true
  Lore:
    Locked: ''
    Unlocked: ''

Can this mystery dust be changed to playerpoints
I want to be like this:

Chocolate Donut:
  Name: '&amp; a chocolate head'
  Rarity: Common
  Enabled: true
  CanBeFound: true
  Purchasable: true
  Point: 15
  Type:
    PlayerPoints:true
    Mystery  Dust:false
    XXX:false
  Lore:
    Locked: ''
    Unlocked: ''
The purchase points are 15 and the purchase type is playerpoints
I hope the author can improve. I'm a Chinese. My English is poor

**Comment by VTSTG233** [comment]
不知道这是不是GitHub特性 这显示没空格

**Comment by OnlyNoobDied** [comment]
Check the config file, you can change the mystery dust storage to playerpoints
```
Cosmetic-Item-Purchase:
  # Set to true allows player to purchase cosmetic items.
  Enabled: true
  # Set the storage where do you want to save mystery dust.
  # Available storages: 'default', 'coinsapi', 'playerpoints', 'vault'.
  # 'default' represent follow player data storage.
  Mystery-Dust-Storage: default
```
